#!/usr/bin/env bash
#configures ufw firewall to block all incoming traffic except tcp 22 433 80

apt-get install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw disable
ufw enable
ufw default deny incoming
#ufw default allow outgoing
ufw allow 22/tcp
ufw allow 433/tcp
ufw allow 80/tcp
