#!/usr/bin/env bash
# run nginx as nginx
sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-available/default
pkill apache2
chmod u+rwx /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sudo -u nginx service nginx start
